parallel_tc_command
FDU-INC/Gemini pull request #2
Opened 2024-09-09 00:44 UTC by zhaozhiyuan0256

parallel the tc commands, accelerate the delay update and the queue filter update, reduce the time to around 3 seconds.

2024-09-09 04:39 UTC, wujs0226 requested changes

2024-09-09 04:39 UTC, wujs0226 commented on system.py
> +            + eth_name
Does the code style modification need a separate branch? @hs-zhuwenjun

2024-09-09 04:43 UTC, zhaozhiyuan0256 commented
This is the automatic formatting of my vscode. This branch mainly performs
parallel operations on the tc command.

Jiasheng Wu ***@***.***> 于2024年9月9日周一 12:39写道：

> ***@***.**** requested changes on this pull request.
> ------------------------------
>
> In system.py
> <https://github.com/FDU-INC/Gemini/pull/2#discussion_r1749544276>:
>
> > @@ -76,49 +79,69 @@ def __init__(
>      def init_eth(self, eth_name):
>          cmd01 = self.ip + ": tc qdisc add dev " + eth_name + " root handle 1: htb"
>          cmd02 = (
> -                self.ip
> -                + ": tc class add dev "
> -                + eth_name
> -                + " parent 1: classid 1:1 htb rate 50mbit"
> +            self.ip
> +            + ": tc class add dev "
> +            + eth_name
>
> Does the code style modification need a separate branch? @hs-zhuwenjun
> <https://github.com/hs-zhuwenjun>
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/FDU-INC/Gemini/pull/2#pullrequestreview-2288795425>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A7XH335VZEUDTNHLCQXJDETZVURAFAVCNFSM6AAAAABN3OZH2GVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDEOBYG44TKNBSGU>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2024-09-09 05:32 UTC, hs-zhuwenjun requested changes

2024-09-09 05:32 UTC, hs-zhuwenjun commented on system.py
> +            for k, v in CURRENT_ROUND_DELAY_UPDATE_CMD.items():
what meaning of 'k' and 'v'?  The name of value should be meaningful.

2024-09-09 09:17 UTC, zhaozhiyuan0256 commented
1. The host.json is modified because the machine is reboot to repair the
broken core network, and after reboot, the interface of kvm to ovs is
changed.
2. DEBUG set to False to make the code in running mode, but not DEBUG mode.
3. The commented out and useless code has been deleted in the new committed
branch.
4. The variable name while lterating over a dictionary has been changed in
the new committed branch.

Zhu, Wenjun ***@***.***> 于2024年9月9日周一 13:32写道：

> ***@***.**** requested changes on this pull request.
> ------------------------------
>
> In hosts.json
> <https://github.com/FDU-INC/Gemini/pull/2#discussion_r1749529087>:
>
> > @@ -24,7 +24,7 @@
>          "host": "host1",
>          "bridge": "br0",
>          "nic_name": "enp1s0",
> -        "if_port": 28,
>
> why modify this value？
> ------------------------------
>
> In hosts.json
> <https://github.com/FDU-INC/Gemini/pull/2#discussion_r1749532292>:
>
> > @@ -36,7 +36,7 @@
>          "host": "host1",
>          "bridge": "br0",
>          "nic_name": "enp1s0",
> -        "if_port": 26,
> +        "if_port": 7,
>
> same as above
> ------------------------------
>
> In system.py
> <https://github.com/FDU-INC/Gemini/pull/2#discussion_r1749532618>:
>
> > @@ -18,19 +18,22 @@
>
>  FAST_ROUTE = True
>
> -DEBUG = True
> +DEBUG = False
>
> same as above
> ------------------------------
>
> In system.py
> <https://github.com/FDU-INC/Gemini/pull/2#discussion_r1749533579>:
>
> >          )
>          self.filter_exist[index] = True
>          do_cmd(cmd)
>
>      def modify_eth_queue_delay(self, eth_name, index, delay):  # ip-str delay-float
> -        cmd = (
> -                self.ip
> -                + ": tc qdisc change dev "
> +        # cmd = (
>
> if this code don‘t need， please remove it.
> ------------------------------
>
> In system.py
> <https://github.com/FDU-INC/Gemini/pull/2#discussion_r1749586733>:
>
> > @@ -1019,8 +1062,13 @@ def run(self):
>              for gs in self.gs_list:
>                  self.node_dict.get(gs.name).set_delay_all()
>
> -            self.renew_delay_update_all_route(t)
> +            print("update queue delay:")
> +            for k, v in CURRENT_ROUND_DELAY_UPDATE_CMD.items():
>
> what meaning of 'k' and 'v'? The name of value should be meaningful.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/FDU-INC/Gemini/pull/2#pullrequestreview-2288777163>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A7XH337JQVCUNDKQWCKPNOLZVUXHZAVCNFSM6AAAAABN3OZH2GVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDEOBYG43TOMJWGM>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2024-10-16 03:06 UTC, hs-zhuwenjun commented
please solve this conflict and pull this merge request again.

2024-10-17 04:33 UTC, zhaozhiyuan0256 commented on system.py
> +            + eth_name
We should use a consistent formatting plugin to standardize the code style.

2024-10-17 04:34 UTC, zhaozhiyuan0256 commented on hosts.json
> -        "if_port": 28,
The configuration has changed after the virtual machine was restarted.

2024-10-17 04:34 UTC, zhaozhiyuan0256 commented on hosts.json
> +        "if_port": 7,
The configuration has changed after the virtual machine was restarted.

2024-10-17 04:35 UTC, zhaozhiyuan0256 commented on system.py
> +DEBUG = False
To ensure that the code can run directly after being cloned to the local machine, it needs to be set to true.

2024-10-17 04:36 UTC, zhaozhiyuan0256 commented on system.py
> +        # cmd = (
It has been deleted.

2024-10-17 04:36 UTC, zhaozhiyuan0256 commented on system.py
> +            for k, v in CURRENT_ROUND_DELAY_UPDATE_CMD.items():
It has been changed to cmd_ip and cmd_txt, which are more descriptive names.

2024-10-17 04:39 UTC, merged